### PR TITLE
WIP: Travis CI

### PR DESCRIPTION
**Pull request by 3noch**
This needs #124 to be merged first.

It seems GHC 7.8.4 is not supported and of course GHC 8.2.1 is not supported yet. GHC 7.10 and 8.0 probably *should* be working but I think tests are failing. We can disable different GHC versions that you don't plan to support.

### CODE REVIEW

**Comment by agentm** [comment]
Nice- thanks for jumping on this. 

Do I need to configure OAuth for the agentm account to work with travis?

**Comment by agentm** [comment]
The tests are likely failing due to being unable to find the cabal package database. I use a cabal sandbox locally, so I just need to add the actual package-db path [here](https://github.com/agentm/project-m36/blob/master/src/lib/ProjectM36/ScriptSession.hs#L47-L51). The path could also be added via environment variable.

I don't mind patching that in after this is merged, though.

I certainly understand why it's valuable to cache the cabal packages, but project-m36 loads itself as a package for the scripting feature tests. Do you think there may be issues due to re-installing the project-m36 package to the database when the version changes.

**Comment by 3noch** [comment]
@agentm Yes you'll need to enable this on Travis CI. You can sign in with your GitHub account and enable this project.

**Comment by agentm** [comment]
Thanks for this patch! The badges should alleviate any build issue fears from newcomers.

**Pull request merged**
