### PR TITLE
Add badges to README

### PR DESCRIPTION
**Pull request by 3noch**

### CODE REVIEW

**Comment by agentm** [comment]
Nice! I wasn't even aware of the packdeps site.

Is it correct that the public domain badge reads "BSD3 License"?

**Comment by 3noch** [comment]
Oops! Fixed.

**Comment by agentm** [comment]
Hi- looking at [the branch to merge](https://github.com/3noch/project-m36/tree/badges), it appears that the badge for the dependency status isn't drawing and is showing text instead. I don't see any obvious error in the markdown. Do you know what's going wrong there?

**Comment by 3noch** [comment]
I've seen that too. Try refreshing your page with cache disabled. I don't know why it does that.

**Comment by 3noch** [comment]
Hmm...now it's happening to me too, and also for the Hackage badge. GitHub is replacing the image source with some githubusercontent URL which I'm betting is the real problem.

**Comment by 3noch** [comment]
And...upon further research, img.shields.io is down!

**Comment by 3noch** [comment]
Looks like it's back up.

**Comment by agentm** [comment]
Thanks- refreshing fixed it for me as well. It looks like it's just a github cacheing issue, so there's nothing to change in the patch.

**Pull request merged**
