### PR TITLE
add prettyprinter

### PR DESCRIPTION
**Pull request by YuMingLiao**
I guess project-m36 could use it. Inclusion dependency is translated in this commit. It is more readable now.

### CODE REVIEW

**Comment by agentm** [comment]
Thanks for the patch! Very cool! I would also like to use this for `:showplan` in tutd.

**Comment by YuMingLiao** [comment]
Glad I could help! 

What is :showplan for? it seems related to DatabaseContextExpression. No document for it.

**Comment by agentm** [comment]
It shows the execution plan for a given database state change (without executing the plan).

**Comment by agentm** [comment]
Thanks for the patch!

**Comment by YuMingLiao** [comment]
Thanks!

caveats: I just tried and It cannot correctly show constraints from `funcdep` command.
It needs a way to print `UnionAttributeNames` but I haven't implemented it. I don't know how to print `AttributeNamesBase` in all cases.

For example: is it like..
{a} `union` {b} == {a, b}
{a} `union` {all but b}
{a} `union` {all from s}
{a} `intersect` ({a} `union` {b})                  ?

**Comment by agentm** [comment]
Shoot- I forgot about functional dependencies. You're right that, currently, there is no TutorialD syntax for these operators, so we will need to decide on which syntax makes sense.

**Comment by agentm** [comment]
I decided on this syntax:

```
x:=s{intersection of {all but sname} {sname}}
y:=s{union of {all but sname} {sname}}
```

which is similar to `all but` syntax. Added and tested with funcdeps in 028a0e4f6e7aa05f317177dfbd183477c3bed806.

**Pull request merged**
