### PR TITLE
Appveyor builder

### PR DESCRIPTION
**Pull request by agentm**
O, the irony- after the endless travis hurdles, appveyor is trivial. 

Appveyor's VMs are able to build Project:M36 without any caching in 22 minutes (60 minutes maximum) which suggests that travis' VMs are comparatively underpowered. 

I need to fix the pkgdb path and some seemingly broken packages- I'm not sure what that is about- but the basics are in place.

### CODE REVIEW

**Comment by agentm** [comment]
@diogob, what do you think? Are there some Windows/appveyor-specific features that we should consider?

**Comment by agentm** [comment]
I fixed the immediate Linux build timeouts by increasing the dependency step timeout. 

I think we will have to wait for travis to fix its macos builder backlog before it's worth investigating what is happening there. If they don't resolve the backlog in the next few days, I will temporarily disable the macos builder.

**Comment by diogob** [comment]
@agentm I have no familiarity with windows/appveyor, but the build time is similar to CircleCI builds. This really makes one think that Travis lags behind in terms of computing power for open source projects. Their macOS backlog still is quite high.

**Comment by agentm** [comment]
Yea, it seems like the macos backlog has only gotten worse in the past week. Still, I appreciate that it is free, so I hold on to hope that we can make it work. I need to get a macos cache in place, then it should be "OK" even if the mac builder runs 16 hours later...

**Comment by agentm** [comment]
Interestingly, the lower resolution of the Windows virtual machine's clock identified a bug in the transaction graph time travel.

I was able to fix the silly package database path issue for the `ScriptSession`. All that remains is a locking bug which I am not able to reproduce in the my own VM. Using a later Windows Server 2016 VM made no difference, so there is perhaps a real file locking bug lurking in the code which I have yet to identify.

`UnlockFileEx: permission denied (The segment is already unlocked.)`

**Pull request merged**
